[project]
name = "mini-vllm"
version = "0.1.0"
description = "A lightweight inference and quantization engine for LLMs."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

dependencies = [
    "torch==2.9.0",
    "pytest>=8.0",
    "transformers>=5.9.0",
    "accelerate",
    "safetensors",
    "datasets",
    "pyyaml",
    "dacite",
    "loguru",
    "rich",
    "tqdm",
    "pydantic",
    "einops",
    "Pillow",
]


[project.optional-dependencies]
flash_attn = [
    "flash-attn",
]
benchmark = [
    "lm-eval",
]
quant = [
    "autoawq",
]
profile = [
    "tensorboard",
    "scalene",
]
monitor = [
    "swanlab",
]
all = [
    "mini-vllm[benchmark,quant,profile,monitor]",
]


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["model*", "engine*", "layers*", "utils*", "kernels*", "eval*"]
