env:
  default_dtype: bfloat16                  # [float16, bfloat16]
  device: cuda:0
  distributed:
    backend: nccl                         # [nccl, gloo]
    init_method: tcp://localhost:29500
    rank: 0
    world_size: 1

inference:
  backend: megakernel_cuda             # [default, megakernel_cuda]
  megakernel_variant: all_combined             # [default, naive, p0, p1, p3, p4, p6, p7, p8, p9, p9_combined, p10, all_combined]
  check_correction: false
  max_new_tokens: 512
  # prompt: "Hello, I am sakuya, I'm a 24 year old student from UCAS University. I like LLM and Infra"
  prompt: "我要去八达岭长城玩，你觉得怎么样？"
  sampling:
    sample_method: greedy                 # [greedy, topp]
    temperature: 1.0
    topk: 10
    topp: 1.0
  use_cuda_graph: true
  cuda_graph_bucket_size: 128
  kv_cache_max_len: 4096
  use_kvcache: true
  use_profile: false
  use_quantized_model: false
  attention_backend: sdpa
  stop_on_eos: true
  use_chat_template: true
  use_thinking: true
  cpu_offload_modules:
    []
    # - model.embed_tokens
    # - lm_head

path:
  baseline_model_path: ~/huggingface/baseline/
  data_path: ''
  model_path: ~/huggingface/Qwen3-0.6B/
  profile_dir: ./log/profile/
  quantized_model_path: ~/huggingface/Qwen3-0.6B-AWQ_Cached

quant:
  apply_clip: true
  backend: triton_wt              # [gemm, triton, triton_wt, triton_wt_fused]
  calibration:
    data: pileval
    max_seq_length: 4096
    n_samples: 32
    split: train
    text_column: text
  export_compatible: false
  group_size: 128                         # [128]
  has_zero_point: true
  layout: Wt                              # [Wt]
  max_chunk_memory: 1073741824
  pack_order: sequential                  # [sequential]
  quant_bits: 4                           # [4]
  quant_method: AWQ                       # [AWQ]
  quant_targets:
  - MLP
  - ATTENTION
  # - LM_HEAD
